//
// Created by gamerpuppy on 7/4/2021.
//

#ifndef STS_LIGHTSPEED_INPUTSTATE_H
#define STS_LIGHTSPEED_INPUTSTATE_H

namespace sts {

    enum class InputState {
        EXECUTING_ACTIONS,

        // player choice actions
        PLAYER_NORMAL,
        CARD_SELECT,

        CHOOSE_STANCE_ACTION, // from stance potion
        CHOOSE_TOOLBOX_COLORLESS_CARD,
        CHOOSE_EXHAUST_POTION_CARDS,
        CHOOSE_GAMBLING_CARDS,
        CHOOSE_ENTROPIC_BREW_DISCARD_POTIONS,
        CHOOSE_DISCARD_CARDS,
        SCRY,

        // random actions
        SELECT_ENEMY_ACTIONS,
        FILL_RANDOM_POTIONS,
        SHUFFLE_INTO_DRAW_BURN,
        SHUFFLE_INTO_DRAW_VOID,
        SHUFFLE_INTO_DRAW_DAZED,
        SHUFFLE_INTO_DRAW_WOUND,
        SHUFFLE_INTO_DRAW_SLIMED,
        SHUFFLE_INTO_DRAW_ALL_STATUS,
        SHUFFLE_CUR_CARD_INTO_DRAW,
        SHUFFLE_DISCARD_TO_DRAW,
        INITIAL_SHUFFLE,

        CREATE_RANDOM_CARD_IN_HAND_POWER,
        CREATE_RANDOM_CARD_IN_HAND_COLORLESS,
        CREATE_RANDOM_CARD_IN_HAND_DEAD_BRANCH,

        SELECT_CARD_IN_HAND_EXHAUST,

        GENERATE_NILRY_CARDS,

        EXHAUST_RANDOM_CARD_IN_HAND,
        SELECT_STRANGE_SPOON_PROC,
        SELECT_ENEMY_THE_SPECIMEN_APPLY_POISON,
        SELECT_WARPED_TONGS_CARD,

        CREATE_ENCHIRIDION_POWER,

        SELECT_CONFUSED_CARD_COST,
    };

}


#endif //STS_LIGHTSPEED_INPUTSTATE_H
