//
// Created by gamerpuppy on 7/8/2021.
//

#ifndef STS_LIGHTSPEED_SAVEFILEMAPPINGS_H
#define STS_LIGHTSPEED_SAVEFILEMAPPINGS_H


#include <nlohmann/json.hpp>

#include <sts/constants/relic_ids.hpp>
#include <sts/constants/potions.hpp>
#include <sts/constants/card_ids.hpp>
#include <sts/constants/monster_encounters.hpp>
#include <sts/constants/events.hpp>

#include <sts/game/neow.hpp>
#include <sts/game/save.hpp>

namespace sts {

    NLOHMANN_JSON_SERIALIZE_ENUM(RelicId, {
        {RelicId::INVALID, nullptr},
        {RelicId::AKABEKO, "Akabeko"},
        {RelicId::ANCHOR, "Anchor"},
        {RelicId::ANCIENT_TEA_SET, "Ancient Tea Set"},
        {RelicId::ART_OF_WAR, "Art of War"},
        {RelicId::ASTROLABE, "Astrolabe"},
        {RelicId::BAG_OF_MARBLES, "Bag of Marbles"},
        {RelicId::BAG_OF_PREPARATION, "Bag of Preparation"},
        {RelicId::BIRD_FACED_URN, "Bird Faced Urn"},
        {RelicId::BLACK_BLOOD, "Black Blood"},
        {RelicId::BLACK_STAR, "Black Star"},
        {RelicId::BLOODY_IDOL, "Bloody Idol"},
        {RelicId::BLOOD_VIAL, "Blood Vial"},
        {RelicId::BLUE_CANDLE, "Blue Candle"},
        {RelicId::BOTTLED_FLAME, "Bottled Flame"},
        {RelicId::BOTTLED_LIGHTNING, "Bottled Lightning"},
        {RelicId::BOTTLED_TORNADO, "Bottled Tornado"},
        {RelicId::BRIMSTONE, "Brimstone"},
        {RelicId::BRONZE_SCALES, "Bronze Scales"},
        {RelicId::BURNING_BLOOD, "Burning Blood"},
        {RelicId::BUSTED_CROWN, "Busted Crown"},
        {RelicId::CALIPERS, "Calipers"},
        {RelicId::CALLING_BELL, "Calling Bell"},
        {RelicId::CAPTAINS_WHEEL, "CaptainsWheel"},
        {RelicId::CAULDRON, "Cauldron"},
        {RelicId::CENTENNIAL_PUZZLE, "Centennial Puzzle"},
        {RelicId::CERAMIC_FISH, "CeramicFish"},
        {RelicId::CHAMPION_BELT, "Champion Belt"},
        {RelicId::CHARONS_ASHES, "Charon's Ashes"},
        {RelicId::CHEMICAL_X, "Chemical X"},
        {RelicId::CLOAK_CLASP, "CloakClasp"},
        {RelicId::CLOCKWORK_SOUVENIR, "ClockworkSouvenir"},
        {RelicId::COFFEE_DRIPPER, "Coffee Dripper"},
        {RelicId::CRACKED_CORE, "Cracked Core"},
        {RelicId::CULTIST_HEADPIECE, "CultistMask"},
        {RelicId::CURSED_KEY, "Cursed Key"},
        {RelicId::DAMARU, "Damaru"},
        {RelicId::DARKSTONE_PERIAPT, "Darkstone Periapt"},
        {RelicId::DATA_DISK, "DataDisk"},
        {RelicId::DEAD_BRANCH, "Dead Branch"},
        {RelicId::DOLLYS_MIRROR, "DollysMirror"},
        {RelicId::DREAM_CATCHER, "Dream Catcher"},
        {RelicId::DUALITY, "Yang"},
        {RelicId::DU_VU_DOLL, "Du-Vu Doll"},
        {RelicId::ECTOPLASM, "Ectoplasm"},
        {RelicId::EMOTION_CHIP, "Emotion Chip"},
        {RelicId::EMPTY_CAGE, "Empty Cage"},
        {RelicId::ENCHIRIDION, "Enchiridion"},
        {RelicId::ETERNAL_FEATHER, "Eternal Feather"},
        {RelicId::FACE_OF_CLERIC, "FaceOfCleric"},
        {RelicId::FOSSILIZED_HELIX, "FossilizedHelix"},
        {RelicId::FROZEN_CORE, "FrozenCore"},
        {RelicId::FROZEN_EGG, "Frozen Egg 2"},
        {RelicId::FROZEN_EYE, "Frozen Eye"},
        {RelicId::FUSION_HAMMER, "Fusion Hammer"},
        {RelicId::GAMBLING_CHIP, "Gambling Chip"},
        {RelicId::GINGER, "Ginger"},
        {RelicId::GIRYA, "Girya"},
        {RelicId::GOLDEN_EYE, "GoldenEye"},
        {RelicId::GOLDEN_IDOL, "Golden Idol"},
        {RelicId::GOLD_PLATED_CABLES, "Cables"},
        {RelicId::GREMLIN_HORN, "Gremlin Horn"},
        {RelicId::GREMLIN_VISAGE, "GremlinMask"},
        {RelicId::HAND_DRILL, "HandDrill"},
        {RelicId::HAPPY_FLOWER, "Happy Flower"},
        {RelicId::HOLY_WATER, "HolyWater"},
        {RelicId::HORN_CLEAT, "HornCleat"},
        {RelicId::HOVERING_KITE, "HoveringKite"},
        {RelicId::ICE_CREAM, "Ice Cream"},
        {RelicId::INCENSE_BURNER, "Incense Burner"},
        {RelicId::INK_BOTTLE, "InkBottle"},
        {RelicId::INSERTER, "Inserter"},
        {RelicId::JUZU_BRACELET, "Juzu Bracelet"},
        {RelicId::KUNAI, "Kunai"},
        {RelicId::LANTERN, "Lantern"},
        {RelicId::LEES_WAFFLE, "Lee's Waffle"},
        {RelicId::LETTER_OPENER, "Letter Opener"},
        {RelicId::LIZARD_TAIL, "Lizard Tail"},
        {RelicId::MAGIC_FLOWER, "Magic Flower"},
        {RelicId::MANGO, "Mango"},
        {RelicId::MARK_OF_PAIN, "Mark of Pain"},
        {RelicId::MARK_OF_THE_BLOOM, "Mark of the Bloom"},
        {RelicId::MATRYOSHKA, "Matryoshka"},
        {RelicId::MAW_BANK, "MawBank"},
        {RelicId::MEAL_TICKET, "MealTicket"},
        {RelicId::MEAT_ON_THE_BONE, "Meat on the Bone"},
        {RelicId::MEDICAL_KIT, "Medical Kit"},
        {RelicId::MELANGE, "Melange"},
        {RelicId::MEMBERSHIP_CARD, "Membership Card"},
        {RelicId::MERCURY_HOURGLASS, "Mercury Hourglass"},
        {RelicId::MOLTEN_EGG, "Molten Egg 2"},
        {RelicId::MUMMIFIED_HAND, "Mummified Hand"},
        {RelicId::MUTAGENIC_STRENGTH, "MutagenicStrength"},
        {RelicId::NLOTHS_GIFT, "Nloth's Gift"},
        {RelicId::NLOTHS_HUNGRY_FACE, "NlothsMask"},
        {RelicId::NECRONOMICON, "Necronomicon"},
        {RelicId::NEOWS_LAMENT, "NeowsBlessing"},
        {RelicId::NILRYS_CODEX, "Nilry's Codex"},
        {RelicId::NINJA_SCROLL, "Ninja Scroll"},
        {RelicId::NUCLEAR_BATTERY, "Nuclear Battery"},
        {RelicId::NUNCHAKU, "Nunchaku"},
        {RelicId::ODDLY_SMOOTH_STONE, "Oddly Smooth Stone"},
        {RelicId::ODD_MUSHROOM, "Odd Mushroom"},
        {RelicId::OLD_COIN, "Old Coin"},
        {RelicId::OMAMORI, "Omamori"},
        {RelicId::ORANGE_PELLETS, "OrangePellets"},
        {RelicId::ORICHALCUM, "Orichalcum"},
        {RelicId::ORNAMENTAL_FAN, "Ornamental Fan"},
        {RelicId::ORRERY, "Orrery"},
        {RelicId::PANDORAS_BOX, "Pandora's Box"},
        {RelicId::PANTOGRAPH, "Pantograph"},
        {RelicId::PAPER_KRANE, "Paper Crane"},
        {RelicId::PAPER_PHROG, "Paper Frog"},
        {RelicId::PEACE_PIPE, "Peace Pipe"},
        {RelicId::PEAR, "Pear"},
        {RelicId::PEN_NIB, "Pen Nib"},
        {RelicId::PHILOSOPHERS_STONE, "Philosopher's Stone"},
        {RelicId::POCKETWATCH, "Pocketwatch"},
        {RelicId::POTION_BELT, "Potion Belt"},
        {RelicId::PRAYER_WHEEL, "Prayer Wheel"},
        {RelicId::PRESERVED_INSECT, "PreservedInsect"},
        {RelicId::PRISMATIC_SHARD, "PrismaticShard"},
        {RelicId::PURE_WATER, "PureWater"},
        {RelicId::QUESTION_CARD, "Question Card"},
        {RelicId::RED_MASK, "Red Mask"},
        {RelicId::RED_SKULL, "Red Skull"},
        {RelicId::REGAL_PILLOW, "Regal Pillow"},
        {RelicId::RING_OF_THE_SERPENT, "Ring of the Serpent"},
        {RelicId::RING_OF_THE_SNAKE, "Ring of the Snake"},
        {RelicId::RUNIC_CAPACITOR, "Runic Capacitor"},
        {RelicId::RUNIC_CUBE, "Runic Cube"},
        {RelicId::RUNIC_DOME, "Runic Dome"},
        {RelicId::RUNIC_PYRAMID, "Runic Pyramid"},
        {RelicId::SACRED_BARK, "SacredBark"},
        {RelicId::SELF_FORMING_CLAY, "Self Forming Clay"},
        {RelicId::SHOVEL, "Shovel"},
        {RelicId::SHURIKEN, "Shuriken"},
        {RelicId::SINGING_BOWL, "Singing Bowl"},
        {RelicId::SLAVERS_COLLAR, "SlaversCollar"},
        {RelicId::SLING_OF_COURAGE, "Sling"},
        {RelicId::SMILING_MASK, "Smiling Mask"},
        {RelicId::SNECKO_EYE, "Snecko Eye"},
        {RelicId::SNECKO_SKULL, "Snake Skull"},
        {RelicId::SOZU, "Sozu"},
        {RelicId::SPIRIT_POOP, "Spirit Poop"},
        {RelicId::SSSERPENT_HEAD, "SsserpentHead"},
        {RelicId::STONE_CALENDAR, "StoneCalendar"},
        {RelicId::STRANGE_SPOON, "Strange Spoon"},
        {RelicId::STRAWBERRY, "Strawberry"},
        {RelicId::STRIKE_DUMMY, "StrikeDummy"},
        {RelicId::SUNDIAL, "Sundial"},
        {RelicId::SYMBIOTIC_VIRUS, "Symbiotic Virus"},
        {RelicId::TEARDROP_LOCKET, "TeardropLocket"},
        {RelicId::THE_ABACUS, "TheAbacus"},
        {RelicId::THE_BOOT, "Boot"},
        {RelicId::THE_COURIER, "The Courier"},
        {RelicId::THE_SPECIMEN, "The Specimen"},
        {RelicId::THREAD_AND_NEEDLE, "Thread and Needle"},
        {RelicId::TINGSHA, "Tingsha"},
        {RelicId::TINY_CHEST, "Tiny Chest"},
        {RelicId::TINY_HOUSE, "Tiny House"},
        {RelicId::TOOLBOX, "Toolbox"},
        {RelicId::TORII, "Torii"},
        {RelicId::TOUGH_BANDAGES, "Tough Bandages"},
        {RelicId::TOXIC_EGG, "Toxic Egg 2"},
        {RelicId::TOY_ORNITHOPTER, "Toy Ornithopter"},
        {RelicId::TUNGSTEN_ROD, "TungstenRod"},
        {RelicId::TURNIP, "Turnip"},
        {RelicId::TWISTED_FUNNEL, "TwistedFunnel"},
        {RelicId::UNCEASING_TOP, "Unceasing Top"},
        {RelicId::VAJRA, "Vajra"},
        {RelicId::VELVET_CHOKER, "Velvet Choker"},
        {RelicId::VIOLET_LOTUS, "VioletLotus"},
        {RelicId::WARPED_TONGS, "WarpedTongs"},
        {RelicId::WAR_PAINT, "War Paint"},
        {RelicId::WHETSTONE, "Whetstone"},
        {RelicId::WHITE_BEAST_STATUE, "White Beast Statue"},
        {RelicId::WING_BOOTS, "WingedGreaves"},
        {RelicId::WRIST_BLADE, "WristBlade"},
        {RelicId::CIRCLET, "Circlet"},
        {RelicId::RED_CIRCLET, "Red Circlet"},
    })

    NLOHMANN_JSON_SERIALIZE_ENUM(CardId, {
        {CardId::INVALID, "INVALID"},
        {CardId::ACCURACY, "Accuracy"},
        {CardId::ACROBATICS, "Acrobatics"},
        {CardId::ADRENALINE, "Adrenaline"},
        {CardId::AFTER_IMAGE, "After Image"},
        {CardId::AGGREGATE, "Aggregate"},
        {CardId::ALCHEMIZE, "Venomology"},
        {CardId::ALL_FOR_ONE, "All For One"},
        {CardId::ALL_OUT_ATTACK, "All Out Attack"},
        {CardId::ALPHA, "Alpha"},
        {CardId::AMPLIFY, "Amplify"},
        {CardId::ANGER, "Anger"},
        {CardId::APOTHEOSIS, "Apotheosis"},
        {CardId::APPARITION, "Ghostly"},
        {CardId::ARMAMENTS, "Armaments"},
        {CardId::ASCENDERS_BANE, "AscendersBane"},
        {CardId::AUTO_SHIELDS, "Auto Shields"},
        {CardId::A_THOUSAND_CUTS, "A Thousand Cuts"},
        {CardId::BACKFLIP, "Backflip"},
        {CardId::BACKSTAB, "Backstab"},
        {CardId::BALL_LIGHTNING, "Ball Lightning"},
        {CardId::BANDAGE_UP, "Bandage Up"},
        {CardId::BANE, "Bane"},
        {CardId::BARRAGE, "Barrage"},
        {CardId::BARRICADE, "Barricade"},
        {CardId::BASH, "Bash"},
        {CardId::BATTLE_HYMN, "BattleHymn"},
        {CardId::BATTLE_TRANCE, "Battle Trance"},
        {CardId::BEAM_CELL, "Beam Cell"},
        {CardId::BECOME_ALMIGHTY, "BecomeAlmighty"},
        {CardId::BERSERK, "Berserk"},
        {CardId::BETA, "Beta"},
        {CardId::BIASED_COGNITION, "Biased Cognition"},
        {CardId::BITE, "Bite"},
        {CardId::BLADE_DANCE, "Blade Dance"},
        {CardId::BLASPHEMY, "Blasphemy"},
        {CardId::BLIND, "Blind"},
        {CardId::BLIZZARD, "Blizzard"},
        {CardId::BLOODLETTING, "Bloodletting"},
        {CardId::BLOOD_FOR_BLOOD, "Blood for Blood"},
        {CardId::BLUDGEON, "Bludgeon"},
        {CardId::BLUR, "Blur"},
        {CardId::BODY_SLAM, "Body Slam"},
        {CardId::BOOT_SEQUENCE, "BootSequence"},
        {CardId::BOUNCING_FLASK, "Bouncing Flask"},
        {CardId::BOWLING_BASH, "BowlingBash"},
        {CardId::BRILLIANCE, "Brilliance"},
        {CardId::BRUTALITY, "Brutality"},
        {CardId::BUFFER, "Buffer"},
        {CardId::BULLET_TIME, "Bullet Time"},
        {CardId::BULLSEYE, "Lockon"},
        {CardId::BURN, "Burn"},
        {CardId::BURNING_PACT, "Burning Pact"},
        {CardId::BURST, "Burst"},
        {CardId::CALCULATED_GAMBLE, "Calculated Gamble"},
        {CardId::CALTROPS, "Caltrops"},
        {CardId::CAPACITOR, "Capacitor"},
        {CardId::CARNAGE, "Carnage"},
        {CardId::CARVE_REALITY, "CarveReality"},
        {CardId::CATALYST, "Catalyst"},
        {CardId::CHAOS, "Chaos"},
        {CardId::CHARGE_BATTERY, "Conserve Battery"},
        {CardId::CHILL, "Chill"},
        {CardId::CHOKE, "Choke"},
        {CardId::CHRYSALIS, "Chrysalis"},
        {CardId::CLASH, "Clash"},
        {CardId::CLAW, "Gash"},
        {CardId::CLEAVE, "Cleave"},
        {CardId::CLOAK_AND_DAGGER, "Cloak And Dagger"},
        {CardId::CLOTHESLINE, "Clothesline"},
        {CardId::CLUMSY, "Clumsy"},
        {CardId::COLD_SNAP, "Cold Snap"},
        {CardId::COLLECT, "Collect"},
        {CardId::COMBUST, "Combust"},
        {CardId::COMPILE_DRIVER, "Compile Driver"},
        {CardId::CONCENTRATE, "Concentrate"},
        {CardId::CONCLUDE, "Conclude"},
        {CardId::CONJURE_BLADE, "ConjureBlade"},
        {CardId::CONSECRATE, "Consecrate"},
        {CardId::CONSUME, "Consume"},
        {CardId::COOLHEADED, "Coolheaded"},
        {CardId::CORE_SURGE, "Core Surge"},
        {CardId::CORPSE_EXPLOSION, "Corpse Explosion"},
        {CardId::CORRUPTION, "Corruption"},
        {CardId::CREATIVE_AI, "Creative AI"},
        {CardId::CRESCENDO, "Crescendo"},
        {CardId::CRIPPLING_CLOUD, "Crippling Poison"},
        {CardId::CRUSH_JOINTS, "CrushJoints"},
        {CardId::CURSE_OF_THE_BELL, "CurseOfTheBell"},
        {CardId::CUT_THROUGH_FATE, "CutThroughFate"},
        {CardId::DAGGER_SPRAY, "Dagger Spray"},
        {CardId::DAGGER_THROW, "Dagger Throw"},
        {CardId::DARKNESS, "Darkness"},
        {CardId::DARK_EMBRACE, "Dark Embrace"},
        {CardId::DARK_SHACKLES, "Dark Shackles"},
        {CardId::DASH, "Dash"},
        {CardId::DAZED, "Dazed"},
        {CardId::DEADLY_POISON, "Deadly Poison"},
        {CardId::DECAY, "Decay"},
        {CardId::DECEIVE_REALITY, "DeceiveReality"},
        {CardId::DEEP_BREATH, "Deep Breath"},
        {CardId::DEFEND_BLUE, "Defend_B"},
        {CardId::DEFEND_GREEN, "Defend_G"},
        {CardId::DEFEND_PURPLE, "Defend_P"},
        {CardId::DEFEND_RED, "Defend_R"},
        {CardId::DEFLECT, "Deflect"},
        {CardId::DEFRAGMENT, "Defragment"},
        {CardId::DEMON_FORM, "Demon Form"},
        {CardId::DEUS_EX_MACHINA, "DeusExMachina"},
        {CardId::DEVA_FORM, "DevaForm"},
        {CardId::DEVOTION, "Devotion"},
        {CardId::DIE_DIE_DIE, "Die Die Die"},
        {CardId::DISARM, "Disarm"},
        {CardId::DISCOVERY, "Discovery"},
        {CardId::DISTRACTION, "Distraction"},
        {CardId::DODGE_AND_ROLL, "Dodge and Roll"},
        {CardId::DOOM_AND_GLOOM, "Doom and Gloom"},
        {CardId::DOPPELGANGER, "Doppelganger"},
        {CardId::DOUBLE_ENERGY, "Double Energy"},
        {CardId::DOUBLE_TAP, "Double Tap"},
        {CardId::DOUBT, "Doubt"},
        {CardId::DRAMATIC_ENTRANCE, "Dramatic Entrance"},
        {CardId::DROPKICK, "Dropkick"},
        {CardId::DUALCAST, "Dualcast"},
        {CardId::DUAL_WIELD, "Dual Wield"},
        {CardId::ECHO_FORM, "Echo Form"},
        {CardId::ELECTRODYNAMICS, "Electrodynamics"},
        {CardId::EMPTY_BODY, "EmptyBody"},
        {CardId::EMPTY_FIST, "EmptyFist"},
        {CardId::EMPTY_MIND, "EmptyMind"},
        {CardId::ENDLESS_AGONY, "Endless Agony"},
        {CardId::ENLIGHTENMENT, "Enlightenment"},
        {CardId::ENTRENCH, "Entrench"},
        {CardId::ENVENOM, "Envenom"},
        {CardId::EQUILIBRIUM, "Undo"},
        {CardId::ERUPTION, "Eruption"},
        {CardId::ESCAPE_PLAN, "Escape Plan"},
        {CardId::ESTABLISHMENT, "Establishment"},
        {CardId::EVALUATE, "Evaluate"},
        {CardId::EVISCERATE, "Eviscerate"},
        {CardId::EVOLVE, "Evolve"},
        {CardId::EXHUME, "Exhume"},
        {CardId::EXPERTISE, "Expertise"},
        {CardId::EXPUNGER, "Expunger"},
        {CardId::FAME_AND_FORTUNE, "FameAndFortune"},
        {CardId::FASTING, "Fasting2"},
        {CardId::FEAR_NO_EVIL, "FearNoEvil"},
        {CardId::FEED, "Feed"},
        {CardId::FEEL_NO_PAIN, "Feel No Pain"},
        {CardId::FIEND_FIRE, "Fiend Fire"},
        {CardId::FINESSE, "Finesse"},
        {CardId::FINISHER, "Finisher"},
        {CardId::FIRE_BREATHING, "Fire Breathing"},
        {CardId::FISSION, "Fission"},
        {CardId::FLAME_BARRIER, "Flame Barrier"},
        {CardId::FLASH_OF_STEEL, "Flash of Steel"},
        {CardId::FLECHETTES, "Flechettes"},
        {CardId::FLEX, "Flex"},
        {CardId::FLURRY_OF_BLOWS, "FlurryOfBlows"},
        {CardId::FLYING_KNEE, "Flying Knee"},
        {CardId::FLYING_SLEEVES, "FlyingSleeves"},
        {CardId::FOLLOW_UP, "FollowUp"},
        {CardId::FOOTWORK, "Footwork"},
        {CardId::FORCE_FIELD, "Force Field"},
        {CardId::FOREIGN_INFLUENCE, "ForeignInfluence"},
        {CardId::FORESIGHT, "Wireheading"},
        {CardId::FORETHOUGHT, "Forethought"},
        {CardId::FTL, "FTL"},
        {CardId::FUSION, "Fusion"},
        {CardId::GENETIC_ALGORITHM, "Genetic Algorithm"},
        {CardId::GHOSTLY_ARMOR, "Ghostly Armor"},
        {CardId::GLACIER, "Glacier"},
        {CardId::GLASS_KNIFE, "Glass Knife"},
        {CardId::GOOD_INSTINCTS, "Good Instincts"},
        {CardId::GO_FOR_THE_EYES, "Go for the Eyes"},
        {CardId::GRAND_FINALE, "Grand Finale"},
        {CardId::HALT, "Halt"},
        {CardId::HAND_OF_GREED, "HandOfGreed"},
        {CardId::HAVOC, "Havoc"},
        {CardId::HEADBUTT, "Headbutt"},
        {CardId::HEATSINKS, "Heatsinks"},
        {CardId::HEAVY_BLADE, "Heavy Blade"},
        {CardId::HEEL_HOOK, "Heel Hook"},
        {CardId::HELLO_WORLD, "Hello World"},
        {CardId::HEMOKINESIS, "Hemokinesis"},
        {CardId::HOLOGRAM, "Hologram"},
        {CardId::HYPERBEAM, "Hyperbeam"},
        {CardId::IMMOLATE, "Immolate"},
        {CardId::IMPATIENCE, "Impatience"},
        {CardId::IMPERVIOUS, "Impervious"},
        {CardId::INDIGNATION, "Indignation"},
        {CardId::INFERNAL_BLADE, "Infernal Blade"},
        {CardId::INFINITE_BLADES, "Infinite Blades"},
        {CardId::INFLAME, "Inflame"},
        {CardId::INJURY, "Injury"},
        {CardId::INNER_PEACE, "InnerPeace"},
        {CardId::INSIGHT, "Insight"},
        {CardId::INTIMIDATE, "Intimidate"},
        {CardId::IRON_WAVE, "Iron Wave"},
        {CardId::JAX, "J.A.X."},
        {CardId::JACK_OF_ALL_TRADES, "Jack Of All Trades"},
        {CardId::JUDGMENT, "Judgement"},
        {CardId::JUGGERNAUT, "Juggernaut"},
        {CardId::JUST_LUCKY, "JustLucky"},
        {CardId::LEAP, "Leap"},
        {CardId::LEG_SWEEP, "Leg Sweep"},
        {CardId::LESSON_LEARNED, "LessonLearned"},
        {CardId::LIKE_WATER, "LikeWater"},
        {CardId::LIMIT_BREAK, "Limit Break"},
        {CardId::LIVE_FOREVER, "LiveForever"},
        {CardId::LOOP, "Loop"},
        {CardId::MACHINE_LEARNING, "Machine Learning"},
        {CardId::MADNESS, "Madness"},
        {CardId::MAGNETISM, "Magnetism"},
        {CardId::MALAISE, "Malaise"},
        {CardId::MASTERFUL_STAB, "Masterful Stab"},
        {CardId::MASTER_OF_STRATEGY, "Master of Strategy"},
        {CardId::MASTER_REALITY, "MasterReality"},
        {CardId::MAYHEM, "Mayhem"},
        {CardId::MEDITATE, "Meditate"},
        {CardId::MELTER, "Melter"},
        {CardId::MENTAL_FORTRESS, "MentalFortress"},
        {CardId::METALLICIZE, "Metallicize"},
        {CardId::METAMORPHOSIS, "Metamorphosis"},
        {CardId::METEOR_STRIKE, "Meteor Strike"},
        {CardId::MIND_BLAST, "Mind Blast"},
        {CardId::MIRACLE, "Miracle"},
        {CardId::MULTI_CAST, "Multi-Cast"},
        {CardId::NECRONOMICURSE, "Necronomicurse"},
        {CardId::NEUTRALIZE, "Neutralize"},
        {CardId::NIGHTMARE, "Night Terror"},
        {CardId::NIRVANA, "Nirvana"},
        {CardId::NORMALITY, "Normality"},
        {CardId::NOXIOUS_FUMES, "Noxious Fumes"},
        {CardId::OFFERING, "Offering"},
        {CardId::OMEGA, "Omega"},
        {CardId::OMNISCIENCE, "Omniscience"},
        {CardId::OUTMANEUVER, "Outmaneuver"},
        {CardId::OVERCLOCK, "Steam Power"},
        {CardId::PAIN, "Pain"},
        {CardId::PANACEA, "Panacea"},
        {CardId::PANACHE, "Panache"},
        {CardId::PANIC_BUTTON, "PanicButton"},
        {CardId::PARASITE, "Parasite"},
        {CardId::PERFECTED_STRIKE, "Perfected Strike"},
        {CardId::PERSEVERANCE, "Perseverance"},
        {CardId::PHANTASMAL_KILLER, "Phantasmal Killer"},
        {CardId::PIERCING_WAIL, "PiercingWail"},
        {CardId::POISONED_STAB, "Poisoned Stab"},
        {CardId::POMMEL_STRIKE, "Pommel Strike"},
        {CardId::POWER_THROUGH, "Power Through"},
        {CardId::PRAY, "Pray"},
        {CardId::PREDATOR, "Predator"},
        {CardId::PREPARED, "Prepared"},
        {CardId::PRESSURE_POINTS, "PathToVictory"},
        {CardId::PRIDE, "Pride"},
        {CardId::PROSTRATE, "Prostrate"},
        {CardId::PROTECT, "Protect"},
        {CardId::PUMMEL, "Pummel"},
        {CardId::PURITY, "Purity"},
        {CardId::QUICK_SLASH, "Quick Slash"},
        {CardId::RAGE, "Rage"},
        {CardId::RAGNAROK, "Ragnarok"},
        {CardId::RAINBOW, "Rainbow"},
        {CardId::RAMPAGE, "Rampage"},
        {CardId::REACH_HEAVEN, "ReachHeaven"},
        {CardId::REAPER, "Reaper"},
        {CardId::REBOOT, "Reboot"},
        {CardId::REBOUND, "Rebound"},
        {CardId::RECKLESS_CHARGE, "Reckless Charge"},
        {CardId::RECURSION, "Redo"},
        {CardId::RECYCLE, "Recycle"},
        {CardId::REFLEX, "Reflex"},
        {CardId::REGRET, "Regret"},
        {CardId::REINFORCED_BODY, "Reinforced Body"},
        {CardId::REPROGRAM, "Reprogram"},
        {CardId::RIDDLE_WITH_HOLES, "Riddle With Holes"},
        {CardId::RIP_AND_TEAR, "Rip and Tear"},
        {CardId::RITUAL_DAGGER, "RitualDagger"},
        {CardId::RUPTURE, "Rupture"},
        {CardId::RUSHDOWN, "Adaptation"},
        {CardId::SADISTIC_NATURE, "Sadistic Nature"},
        {CardId::SAFETY, "Safety"},
        {CardId::SANCTITY, "Sanctity"},
        {CardId::SANDS_OF_TIME, "SandsOfTime"},
        {CardId::SASH_WHIP, "SashWhip"},
        {CardId::SCRAPE, "Scrape"},
        {CardId::SCRAWL, "Scrawl"},
        {CardId::SEARING_BLOW, "Searing Blow"},
        {CardId::SECOND_WIND, "Second Wind"},
        {CardId::SECRET_TECHNIQUE, "Secret Technique"},
        {CardId::SECRET_WEAPON, "Secret Weapon"},
        {CardId::SEEING_RED, "Seeing Red"},
        {CardId::SEEK, "Seek"},
        {CardId::SELF_REPAIR, "Self Repair"},
        {CardId::SENTINEL, "Sentinel"},
        {CardId::SETUP, "Setup"},
        {CardId::SEVER_SOUL, "Sever Soul"},
        {CardId::SHAME, "Shame"},
        {CardId::SHIV, "Shiv"},
        {CardId::SHOCKWAVE, "Shockwave"},
        {CardId::SHRUG_IT_OFF, "Shrug It Off"},
        {CardId::SIGNATURE_MOVE, "SignatureMove"},
        {CardId::SIMMERING_FURY, "Vengeance"},
        {CardId::SKEWER, "Skewer"},
        {CardId::SKIM, "Skim"},
        {CardId::SLICE, "Slice"},
        {CardId::SLIMED, "Slimed"},
        {CardId::SMITE, "Smite"},
        {CardId::SNEAKY_STRIKE, "Underhanded Strike"},
        {CardId::SPIRIT_SHIELD, "SpiritShield"},
        {CardId::SPOT_WEAKNESS, "Spot Weakness"},
        {CardId::STACK, "Stack"},
        {CardId::STATIC_DISCHARGE, "Static Discharge"},
        {CardId::STEAM_BARRIER, "Steam"},
        {CardId::STORM, "Storm"},
        {CardId::STORM_OF_STEEL, "Storm of Steel"},
        {CardId::STREAMLINE, "Streamline"},
        {CardId::STRIKE_BLUE, "Strike_B"},
        {CardId::STRIKE_GREEN, "Strike_G"},
        {CardId::STRIKE_PURPLE, "Strike_P"},
        {CardId::STRIKE_RED, "Strike_R"},
        {CardId::STUDY, "Study"},
        {CardId::SUCKER_PUNCH, "Sucker Punch"},
        {CardId::SUNDER, "Sunder"},
        {CardId::SURVIVOR, "Survivor"},
        {CardId::SWEEPING_BEAM, "Sweeping Beam"},
        {CardId::SWIFT_STRIKE, "Swift Strike"},
        {CardId::SWIVEL, "Swivel"},
        {CardId::SWORD_BOOMERANG, "Sword Boomerang"},
        {CardId::TACTICIAN, "Tactician"},
        {CardId::TALK_TO_THE_HAND, "TalkToTheHand"},
        {CardId::TANTRUM, "Tantrum"},
        {CardId::TEMPEST, "Tempest"},
        {CardId::TERROR, "Terror"},
        {CardId::THE_BOMB, "The Bomb"},
        {CardId::THINKING_AHEAD, "Thinking Ahead"},
        {CardId::THIRD_EYE, "ThirdEye"},
        {CardId::THROUGH_VIOLENCE, "ThroughViolence"},
        {CardId::THUNDERCLAP, "Thunderclap"},
        {CardId::THUNDER_STRIKE, "Thunder Strike"},
        {CardId::TOOLS_OF_THE_TRADE, "Tools of the Trade"},
        {CardId::TRANQUILITY, "ClearTheMind"},
        {CardId::TRANSMUTATION, "Transmutation"},
        {CardId::TRIP, "Trip"},
        {CardId::TRUE_GRIT, "True Grit"},
        {CardId::TURBO, "Turbo"},
        {CardId::TWIN_STRIKE, "Twin Strike"},
        {CardId::UNLOAD, "Unload"},
        {CardId::UPPERCUT, "Uppercut"},
        {CardId::VAULT, "Vault"},
        {CardId::VIGILANCE, "Vigilance"},
        {CardId::VIOLENCE, "Violence"},
        {CardId::VOID, "Void"},
        {CardId::WALLOP, "Wallop"},
        {CardId::WARCRY, "Warcry"},
        {CardId::WAVE_OF_THE_HAND, "WaveOfTheHand"},
        {CardId::WEAVE, "Weave"},
        {CardId::WELL_LAID_PLANS, "Well Laid Plans"},
        {CardId::WHEEL_KICK, "WheelKick"},
        {CardId::WHIRLWIND, "Whirlwind"},
        {CardId::WHITE_NOISE, "White Noise"},
        {CardId::WILD_STRIKE, "Wild Strike"},
        {CardId::WINDMILL_STRIKE, "WindmillStrike"},
        {CardId::WISH, "Wish"},
        {CardId::WORSHIP, "Worship"},
        {CardId::WOUND, "Wound"},
        {CardId::WRAITH_FORM, "Wraith Form v2"},
        {CardId::WREATH_OF_FLAME, "WreathOfFlame"},
        {CardId::WRITHE, "Writhe"},
        {CardId::ZAP, "Zap"},
    })

    NLOHMANN_JSON_SERIALIZE_ENUM(Event, {
        {Event::INVALID, nullptr},
        {Event::MONSTER, "MONSTER"},
        {Event::TREASURE, "TREASURE"},
        {Event::SHOP, "SHOP"},
        {Event::OMINOUS_FORGE, "Accursed Blacksmith"},
        {Event::PLEADING_VAGRANT, "Addict"},
        {Event::ANCIENT_WRITING, "Back to Basics"},
        {Event::OLD_BEGGAR, "Beggar"},
        {Event::BIG_FISH, "Big Fish"},
        {Event::BONFIRE_SPIRITS, "Bonfire Elementals"},
        {Event::COLOSSEUM, "Colosseum"},
        {Event::CURSED_TOME, "Cursed Tome"},
        {Event::DEAD_ADVENTURER, "Dead Adventurer"},
        {Event::DESIGNER_IN_SPIRE, "Designer"},
        {Event::AUGMENTER, "Drug Dealer"},
        {Event::DUPLICATOR, "Duplicator"},
        {Event::FACE_TRADER, "FaceTrader"},
        {Event::FALLING, "Falling"},
        {Event::FORGOTTEN_ALTAR, "Forgotten Altar"},
        {Event::THE_DIVINE_FOUNTAIN, "Fountain of Cleansing"},
        {Event::GHOSTS, "Ghosts"},
        {Event::GOLDEN_IDOL, "Golden Idol"},
        {Event::GOLDEN_SHRINE, "Golden Shrine"},
        {Event::WING_STATUE, "Golden Wing"},
        {Event::KNOWING_SKULL, "Knowing Skull"},
        {Event::LAB, "Lab"},
        {Event::THE_SSSSSERPENT, "Liars Game"},
        {Event::LIVING_WALL, "Living Wall"},
        {Event::MASKED_BANDITS, "Masked Bandits"},
        {Event::MATCH_AND_KEEP, "Match and Keep"},
        {Event::MINDBLOOM, "MindBloom"},
        {Event::HYPNOTIZING_COLORED_MUSHROOMS, "Mushrooms"},
        {Event::MYSTERIOUS_SPHERE, "Mysterious Sphere"},
        {Event::THE_NEST, "Nest"},
        {Event::NLOTH, "N\u0027loth"},
        {Event::NOTE_FOR_YOURSELF, "NoteForYourself"},
        {Event::PURIFIER, "Purifier"},
        {Event::SCRAP_OOZE, "Scrap Ooze"},
        {Event::SECRET_PORTAL, "SecretPortal"},
        {Event::SENSORY_STONE, "Sensory Stone"},
        {Event::SHINING_LIGHT, "Shining Light"},
        {Event::THE_CLERIC, "The Cleric"},
        {Event::THE_JOUST, "The Joust"},
        {Event::THE_LIBRARY, "The Library"},
        {Event::THE_MAUSOLEUM, "The Mausoleum"},
        {Event::THE_MOAI_HEAD, "The Moai Head"},
        {Event::THE_WOMAN_IN_BLUE, "The Woman in Blue"},
        {Event::TOMB_OF_LORD_RED_MASK, "Tomb of Lord Red Mask"},
        {Event::TRANSMORGRIFIER, "Transmorgrifier"},
        {Event::UPGRADE_SHRINE, "Upgrade Shrine"},
        {Event::VAMPIRES, "Vampires"},
        {Event::WE_MEET_AGAIN, "WeMeetAgain"},
        {Event::WHEEL_OF_CHANGE, "Wheel of Change"},
        {Event::WINDING_HALLS, "Winding Halls"},
        {Event::WORLD_OF_GOOP, "World of Goop"},
    })

    NLOHMANN_JSON_SERIALIZE_ENUM(MonsterEncounter, {
        {MonsterEncounter::INVALID, nullptr},
        {MonsterEncounter::AUTOMATON, "Automaton"},
        {MonsterEncounter::AWAKENED_ONE, "Awakened One"},
        {MonsterEncounter::BLUE_SLAVER, "Blue Slaver"},
        {MonsterEncounter::BOOK_OF_STABBING, "Book of Stabbing"},
        {MonsterEncounter::CENTURION_AND_HEALER, "Centurion and Healer"},
        {MonsterEncounter::CHAMP, "Champ"},
        {MonsterEncounter::CHOSEN, "Chosen"},
        {MonsterEncounter::CHOSEN_AND_BYRDS, "Chosen and Byrds"},
        {MonsterEncounter::COLLECTOR, "Collector"},
        {MonsterEncounter::CULTIST, "Cultist"},
        {MonsterEncounter::CULTIST_AND_CHOSEN, "Cultist and Chosen"},
        {MonsterEncounter::DONU_AND_DECA, "Donu and Deca"},
        {MonsterEncounter::EXORDIUM_THUGS, "Exordium Thugs"},
        {MonsterEncounter::EXORDIUM_WILDLIFE, "Exordium Wildlife"},
        {MonsterEncounter::FOUR_SHAPES, "4 Shapes"},
        {MonsterEncounter::GIANT_HEAD, "Giant Head"},
        {MonsterEncounter::GREMLIN_GANG, "Gremlin Gang"},
        {MonsterEncounter::GREMLIN_LEADER, "Gremlin Leader"},
        {MonsterEncounter::GREMLIN_NOB, "Gremlin Nob"},
        {MonsterEncounter::HEXAGHOST, "Hexaghost"},
        {MonsterEncounter::JAW_WORM, "Jaw Worm"},
        {MonsterEncounter::JAW_WORM_HORDE, "Jaw Worm Horde"},
        {MonsterEncounter::LAGAVULIN, "Lagavulin"},
        {MonsterEncounter::LARGE_SLIME, "Large Slime"},
        {MonsterEncounter::LOOTER, "Looter"},
        {MonsterEncounter::LOTS_OF_SLIMES, "Lots of Slimes"},
        {MonsterEncounter::MAW, "Maw"},
        {MonsterEncounter::NEMESIS, "Nemesis"},
        {MonsterEncounter::ORB_WALKER, "Orb Walker"},
        {MonsterEncounter::RED_SLAVER, "Red Slaver"},
        {MonsterEncounter::REPTOMANCER, "Reptomancer"},
        {MonsterEncounter::SENTRY_AND_SPHERE, "Sentry and Sphere"},
        {MonsterEncounter::SHELLED_PARASITE_AND_FUNGI, "Shelled Parasite and Fungi"},
        {MonsterEncounter::SHELL_PARASITE, "Shell Parasite"},
        {MonsterEncounter::SHIELD_AND_SPEAR, "Shield and Spear"},
        {MonsterEncounter::SLAVERS, "Slavers"},
        {MonsterEncounter::SLIME_BOSS, "Slime Boss"},
        {MonsterEncounter::SMALL_SLIMES, "Small Slimes"},
        {MonsterEncounter::SNAKE_PLANT, "Snake Plant"},
        {MonsterEncounter::SNECKO, "Snecko"},
        {MonsterEncounter::SPHERE_AND_TWO_SHAPES, "Sphere and Two Shapes"},
        {MonsterEncounter::SPHERIC_GUARDIAN, "Spheric Guardian"},
        {MonsterEncounter::SPIRE_GROWTH, "Spire Growth"},
        {MonsterEncounter::THE_GUARDIAN, "The Guardian"},
        {MonsterEncounter::THE_HEART, "The Heart"},
        {MonsterEncounter::THREE_BYRDS, "3 Byrds"},
        {MonsterEncounter::THREE_CULTIST, "3 Cultists"},
        {MonsterEncounter::THREE_DARKLINGS, "3 Darklings"},
        {MonsterEncounter::THREE_LOUSE, "3 Louse"},
        {MonsterEncounter::THREE_SENTRIES, "3 Sentries"},
        {MonsterEncounter::THREE_SHAPES, "3 Shapes"},
        {MonsterEncounter::TIME_EATER, "Time Eater"},
        {MonsterEncounter::TRANSIENT, "Transient"},
        {MonsterEncounter::TWO_FUNGI_BEASTS, "2 Fungi Beasts"},
        {MonsterEncounter::TWO_LOUSE, "2 Louse"},
        {MonsterEncounter::TWO_THIEVES, "2 Thieves"},
        {MonsterEncounter::WRITHING_MASS, "Writhing Mass"},
    })

    NLOHMANN_JSON_SERIALIZE_ENUM(Potion, {
        {Potion::INVALID, nullptr},
        {Potion::EMPTY_POTION_SLOT, "Potion Slot"},
        {Potion::AMBROSIA, "Ambrosia"},
        {Potion::ANCIENT_POTION, "Ancient Potion"},
        {Potion::ATTACK_POTION, "AttackPotion"},
        {Potion::BLESSING_OF_THE_FORGE, "BlessingOfTheForge"},
        {Potion::BLOCK_POTION, "Block Potion"},
        {Potion::BLOOD_POTION, "BloodPotion"},
        {Potion::BOTTLED_MIRACLE, "BottledMiracle"},
        {Potion::COLORLESS_POTION, "ColorlessPotion"},
        {Potion::CULTIST_POTION, "CultistPotion"},
        {Potion::CUNNING_POTION, "CunningPotion"},
        {Potion::DEXTERITY_POTION, "Dexterity Potion"},
        {Potion::DISTILLED_CHAOS, "DistilledChaos"},
        {Potion::DUPLICATION_POTION, "DuplicationPotion"},
        {Potion::ELIXIR_POTION, "ElixirPotion"},
        {Potion::ENERGY_POTION, "Energy Potion"},
        {Potion::ENTROPIC_BREW, "EntropicBrew"},
        {Potion::ESSENCE_OF_DARKNESS, "EssenceOfDarkness"},
        {Potion::ESSENCE_OF_STEEL, "EssenceOfSteel"},
        {Potion::EXPLOSIVE_POTION, "Explosive Potion"},
        {Potion::FAIRY_POTION, "FairyPotion"},
        {Potion::FEAR_POTION, "FearPotion"},
        {Potion::FIRE_POTION, "Fire Potion"},
        {Potion::FLEX_POTION, "SteroidPotion"},
        {Potion::FOCUS_POTION, "FocusPotion"},
        {Potion::FRUIT_JUICE, "Fruit Juice"},
        {Potion::GAMBLERS_BREW, "GamblersBrew"},
        {Potion::GHOST_IN_A_JAR, "GhostInAJar"},
        {Potion::HEART_OF_IRON, "HeartOfIron"},
        {Potion::LIQUID_BRONZE, "LiquidBronze"},
        {Potion::LIQUID_MEMORIES, "LiquidMemories"},
        {Potion::POISON_POTION, "Poison Potion"},
        {Potion::POTION_OF_CAPACITY, "PotionOfCapacity"},
        {Potion::POWER_POTION, "PowerPotion"},
        {Potion::REGEN_POTION, "Regen Potion"},
        {Potion::SKILL_POTION, "SkillPotion"},
        {Potion::SMOKE_BOMB, "SmokeBomb"},
        {Potion::SNECKO_OIL, "SneckoOil"},
        {Potion::SPEED_POTION, "SpeedPotion"},
        {Potion::STANCE_POTION, "StancePotion"},
        {Potion::STRENGTH_POTION, "Strength Potion"},
        {Potion::SWIFT_POTION, "Swift Potion"},
        {Potion::WEAK_POTION, "Weak Potion"},
    })

    namespace Neow {

        NLOHMANN_JSON_SERIALIZE_ENUM(Bonus, {
            {Bonus::INVALID, nullptr},
            {Bonus::RANDOM_COLORLESS_2, "RANDOM_COLORLESS_2"},
            {Bonus::THREE_CARDS, "THREE_CARDS"},
            {Bonus::ONE_RANDOM_RARE_CARD, "ONE_RANDOM_RARE_CARD"},
            {Bonus::REMOVE_CARD, "REMOVE_CARD"},
            {Bonus::UPGRADE_CARD, "UPGRADE_CARD"},
            {Bonus::RANDOM_COLORLESS, "RANDOM_COLORLESS"},
            {Bonus::TRANSFORM_CARD, "TRANSFORM_CARD"},
            {Bonus::THREE_SMALL_POTIONS, "THREE_SMALL_POTIONS"},
            {Bonus::RANDOM_COMMON_RELIC, "RANDOM_COMMON_RELIC"},
            {Bonus::TEN_PERCENT_HP_BONUS, "TEN_PERCENT_HP_BONUS"},
            {Bonus::HUNDRED_GOLD, "HUNDRED_GOLD"},
            {Bonus::THREE_ENEMY_KILL, "THREE_ENEMY_KILL"},
            {Bonus::REMOVE_TWO, "REMOVE_TWO"},
            {Bonus::TRANSFORM_TWO_CARDS, "TRANSFORM_TWO_CARDS"},
            {Bonus::ONE_RARE_RELIC, "ONE_RARE_RELIC"},
            {Bonus::THREE_RARE_CARDS, "THREE_RARE_CARDS"},
            {Bonus::TWO_FIFTY_GOLD, "TWO_FIFTY_GOLD"},
            {Bonus::TWENTY_PERCENT_HP_BONUS, "TWENTY_PERCENT_HP_BONUS"},
            {Bonus::BOSS_RELIC, "BOSS_RELIC"},
        })

        NLOHMANN_JSON_SERIALIZE_ENUM(Drawback, {
            {Drawback::INVALID, nullptr},
            {Drawback::NONE, "NONE"},
            {Drawback::TEN_PERCENT_HP_LOSS, "TEN_PERCENT_HP_LOSS"},
            {Drawback::NO_GOLD, "NO_GOLD"},
            {Drawback::CURSE, "CURSE"},
            {Drawback::PERCENT_DAMAGE, "PERCENT_DAMAGE"},
            {Drawback::LOSE_STARTER_RELIC, "LOSE_STARTER_RELIC"},
        })

    }

    namespace Save {

        NLOHMANN_JSON_SERIALIZE_ENUM(RoomType, {
            {RoomType::INVALID, nullptr},
            {RoomType::EMPTY_ROOM, "com.megacrit.cardcrawl.rooms.EmptyRoom"},
            {RoomType::EVENT_ROOM, "com.megacrit.cardcrawl.rooms.EventRoom"},
            {RoomType::MONSTER_ROOM, "com.megacrit.cardcrawl.rooms.MonsterRoom"},
            {RoomType::MONSTER_ROOM_BOSS, "com.megacrit.cardcrawl.rooms.MonsterRoomBoss"},
            {RoomType::MONSTER_ROOM_ELITE, "com.megacrit.cardcrawl.rooms.MonsterRoomElite"},
            {RoomType::REST_ROOM, "com.megacrit.cardcrawl.rooms.RestRoom"},
            {RoomType::SHOP_ROOM, "com.megacrit.cardcrawl.rooms.ShopRoom"},
            {RoomType::TREASURE_ROOM, "com.megacrit.cardcrawl.rooms.TreasureRoom"},
            {RoomType::TREASURE_ROOM_BOSS, "com.megacrit.cardcrawl.rooms.TreasureRoomBoss"},
            {RoomType::TRUE_VICTORY_ROOM, "com.megacrit.cardcrawl.rooms.TrueVictoryRoom"},
            {RoomType::VICTORY_ROOM, "com.megacrit.cardcrawl.rooms.VictoryRoom"},
        })

        NLOHMANN_JSON_SERIALIZE_ENUM(CombatRewardType, {
            {CombatRewardType::INVALID, nullptr},
            {CombatRewardType::GOLD, "GOLD"},
            {CombatRewardType::CARD, "CARD"},
            {CombatRewardType::POTION, "POTION"},
            {CombatRewardType::RELIC, "RELIC"},
            {CombatRewardType::STOLEN_GOLD, "STOLEN_GOLD"},
            {CombatRewardType::EMERALD_KEY, "EMERALD_KEY"},
            {CombatRewardType::SAPPHIRE_KEY, "SAPPHIRE_KEY"},
        })

        void from_json(const nlohmann::json &j, CombatReward &r) {
            j.at("type").get_to(r.type);

            switch (r.type) {
                case CombatRewardType::STOLEN_GOLD:
                case CombatRewardType::GOLD:
                    r.bonusGold = 0;
                    j.at("amount").get_to(r.amount);
                    j.at("bonusGold").get_to(r.bonusGold);
                    break;

                case CombatRewardType::CARD:
                    j.at("id").get_to(r.cardId);
                    break;

                case CombatRewardType::POTION:
                    j.at("id").get_to(r.potionId);
                    break;

                case CombatRewardType::RELIC:
                    j.at("id").get_to(r.relicId);
                    break;

                default:
                    break;
            }
        }

    }


}

#endif //STS_LIGHTSPEED_SAVEFILEMAPPINGS_H
